import {
  faBagShopping,
  faBaby,
  faBandage,
  faBicycle,
  faBook,
  faBriefcase,
  faBus,
  faCamera,
  faCar,
  faCartShopping,
  faCat,
  faChild,
  faChartLine,
  faCoffee,
  faCouch,
  faCreditCard,
  faDog,
  faDumbbell,
  faFileInvoiceDollar,
  faFilm,
  faFutbol,
  faGamepad,
  faGasPump,
  faGift,
  faGraduationCap,
  faHammer,
  faHandHoldingHeart,
  faHamburger,
  faHeadphones,
  faHeart,
  faHeartPulse,
  faHotel,
  faHouse,
  faLandmark,
  faLaptop,
  faLeaf,
  faMobileScreen,
  faMoneyBill,
  faMotorcycle,
  faMusic,
  faPaintRoller,
  faPaw,
  faPills,
  faPizzaSlice,
  faPlane,
  faRunning,
  faScissors,
  faSeedling,
  faShirt,
  faSpa,
  faStethoscope,
  faStore,
  faSuitcase,
  faSwimmer,
  faSyringe,
  faTag,
  faTools,
  faTrain,
  faTv,
  faUtensils,
  faWifi,
  faWineGlass,
  faBasketball,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import type { CategoryIconId } from "../types";

const ICON_MAP: Record<string, IconDefinition> = {
  // FA icon names
  "bag-shopping": faBagShopping,
  baby: faBaby,
  bandage: faBandage,
  bicycle: faBicycle,
  book: faBook,
  briefcase: faBriefcase,
  bus: faBus,
  camera: faCamera,
  car: faCar,
  "cart-shopping": faCartShopping,
  cat: faCat,
  child: faChild,
  "chart-line": faChartLine,
  coffee: faCoffee,
  couch: faCouch,
  "credit-card": faCreditCard,
  dog: faDog,
  dumbbell: faDumbbell,
  "file-invoice-dollar": faFileInvoiceDollar,
  film: faFilm,
  futbol: faFutbol,
  gamepad: faGamepad,
  "gas-pump": faGasPump,
  gift: faGift,
  "graduation-cap": faGraduationCap,
  hammer: faHammer,
  "hand-holding-heart": faHandHoldingHeart,
  hamburger: faHamburger,
  headphones: faHeadphones,
  heart: faHeart,
  "heart-pulse": faHeartPulse,
  hotel: faHotel,
  house: faHouse,
  landmark: faLandmark,
  laptop: faLaptop,
  leaf: faLeaf,
  "mobile-screen": faMobileScreen,
  "money-bill": faMoneyBill,
  motorcycle: faMotorcycle,
  music: faMusic,
  "paint-roller": faPaintRoller,
  paw: faPaw,
  pills: faPills,
  "pizza-slice": faPizzaSlice,
  plane: faPlane,
  running: faRunning,
  scissors: faScissors,
  seedling: faSeedling,
  shirt: faShirt,
  spa: faSpa,
  stethoscope: faStethoscope,
  store: faStore,
  suitcase: faSuitcase,
  swimmer: faSwimmer,
  syringe: faSyringe,
  tag: faTag,
  tools: faTools,
  train: faTrain,
  tv: faTv,
  utensils: faUtensils,
  wifi: faWifi,
  "wine-glass": faWineGlass,
  basketball: faBasketball,

  // Legacy IDs (backward compat with stored data)
  groceries: faCartShopping,
  food: faUtensils,
  travel: faPlane,
  shopping: faBagShopping,
  bills: faFileInvoiceDollar,
  health: faHeartPulse,
  entertainment: faFilm,
  work: faBriefcase,
  other: faTag,
};

export function CategoryIcon({ iconId }: { iconId: CategoryIconId }) {
  const icon = ICON_MAP[iconId] ?? faTag;
  return <FontAwesomeIcon icon={icon} aria-hidden="true" fixedWidth />;
}
